#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <vector>

DustCrateAudioProcessor::DustCrateAudioProcessor()
    : AudioProcessor(BusesProperties()
          .withOutput("Output", juce::AudioChannelSet::stereo(), true)),
      apvts(*this, nullptr, "Parameters", createParameterLayout())
{
    formatManager.registerBasicFormats();

    for (int i = 0; i < 16; ++i)
        synth.addVoice(new SampleVoice());
    synth.addSound(new SampleSound());

    // Load factory pack from embedded BinaryData (if present)
    // BinaryData::factory_pack_json is generated by juce_add_binary_data in CMakeLists.
    // Graceful no-op if the symbol doesn't exist yet (pre-asset build).
#if defined (BinaryData::namedResourceList)
    sampleLibrary.loadPackFromBinaryData(
        BinaryData::factory_pack_json,
        BinaryData::factory_pack_jsonSize);
#endif
}

DustCrateAudioProcessor::~DustCrateAudioProcessor() {}

void DustCrateAudioProcessor::prepareToPlay(double sampleRate, int samplesPerBlock)
{
    currentSampleRate = sampleRate;
    synth.setCurrentPlaybackSampleRate(sampleRate);
    characterProcessor.prepare(sampleRate, samplesPerBlock);
}

void DustCrateAudioProcessor::releaseResources() {}

//==============================================================================
void DustCrateAudioProcessor::updateVoiceParameters()
{
    const float attack   = *apvts.getRawParameterValue("attack");
    const float decay    = *apvts.getRawParameterValue("decay");
    const float sustain  = *apvts.getRawParameterValue("sustain");
    const float release  = *apvts.getRawParameterValue("release");
    const float cutoff   = *apvts.getRawParameterValue("filterCutoff");
    const float res      = *apvts.getRawParameterValue("filterRes");
    const int   fType    = (int) *apvts.getRawParameterValue("filterType");
    const float pitch    = *apvts.getRawParameterValue("pitchSemitones");
    const float drift    = *apvts.getRawParameterValue("driftAmount");

    for (int i = 0; i < synth.getNumVoices(); ++i)
        if (auto* v = dynamic_cast<SampleVoice*>(synth.getVoice(i)))
        {
            v->setADSR(attack, decay, sustain, release);
            v->setFilter(cutoff, res, fType == 1);
            v->setPitchShift(pitch);
            v->setDriftRatio(drift);
        }
}

void DustCrateAudioProcessor::processBlock(juce::AudioBuffer<float>& buffer,
                                           juce::MidiBuffer& midiMessages)
{
    juce::ScopedNoDenormals noDenormals;
    buffer.clear();

    {
        const juce::ScopedLock sl (synthLock);

        // Merge UI-generated preview MIDI
        if (! pendingMidi.isEmpty())
        {
            for (const auto meta : pendingMidi)
                midiMessages.addEvent(meta.getMessage(), meta.samplePosition);
            pendingMidi.clear();
        }

        // Push APVTS params into every voice before rendering
        updateVoiceParameters();

        synth.renderNextBlock(buffer, midiMessages, 0, buffer.getNumSamples());
    }

    // Character processing (outside synth lock; operates only on the buffer)
    characterProcessor.setDrift    (*apvts.getRawParameterValue("driftAmount"));
    characterProcessor.setVHS      (*apvts.getRawParameterValue("vhsAmount"));
    characterProcessor.setCassette (*apvts.getRawParameterValue("cassetteAmount"));
    characterProcessor.setNoise    (*apvts.getRawParameterValue("noiseLevel"));
    characterProcessor.processBlock(buffer);

    // Feed waveform display (L channel only)
    if (onAudioBlock)
        onAudioBlock(buffer.getReadPointer(0), buffer.getNumSamples());
}

//==============================================================================
bool DustCrateAudioProcessor::selectSample(const juce::String& filePath, int rootNote)
{
    const juce::File file(filePath);
    const int numVoices = synth.getNumVoices();

    std::vector<std::unique_ptr<juce::AudioFormatReader>> readers;
    readers.resize((size_t) numVoices);

    bool anyLoaded = false;
    for (int i = 0; i < numVoices; ++i)
    {
        readers[(size_t) i].reset(formatManager.createReaderFor(file));
        if (readers[(size_t) i] != nullptr)
            anyLoaded = true;
    }
    if (! anyLoaded) return false;

    const juce::ScopedLock sl (synthLock);
    for (int i = 0; i < numVoices; ++i)
        if (auto* v = dynamic_cast<SampleVoice*>(synth.getVoice(i)))
            if (readers[(size_t) i] != nullptr)
                v->setReader(readers[(size_t) i].release(), rootNote);

    return true;
}

void DustCrateAudioProcessor::triggerSample(const juce::String& filePath,
                                            int midiNote, float velocity)
{
    if (! selectSample(filePath, midiNote))
        return;

    const juce::ScopedLock sl (synthLock);
    pendingMidi.addEvent(juce::MidiMessage::noteOn(1, midiNote, velocity), 0);
}

void DustCrateAudioProcessor::stopAllVoices()
{
    const juce::ScopedLock sl (synthLock);
    synth.allNotesOff(0, true);
}

//==============================================================================
juce::AudioProcessorValueTreeState::ParameterLayout
DustCrateAudioProcessor::createParameterLayout()
{
    std::vector<std::unique_ptr<juce::RangedAudioParameter>> params;

    params.push_back(std::make_unique<juce::AudioParameterFloat>("attack",  "Attack",  0.001f, 2.0f,  0.01f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("decay",   "Decay",   0.001f, 2.0f,  0.10f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("sustain", "Sustain", 0.0f,   1.0f,  0.80f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("release", "Release", 0.001f, 4.0f,  0.20f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("filterCutoff", "Filter Cutoff", 20.0f, 20000.0f, 8000.0f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("filterRes",    "Filter Resonance", 0.1f, 10.0f, 1.0f));
    params.push_back(std::make_unique<juce::AudioParameterChoice>("filterType", "Filter Type",
        juce::StringArray { "Lowpass", "Highpass" }, 0));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("pitchSemitones", "Pitch (semitones)", -24.0f, 24.0f, 0.0f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("noiseLevel",    "Noise Level",  0.0f, 1.0f, 0.0f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("driftAmount",   "Drift",    0.0f, 1.0f, 0.0f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("vhsAmount",     "VHS",      0.0f, 1.0f, 0.0f));
    params.push_back(std::make_unique<juce::AudioParameterFloat>("cassetteAmount","Cassette", 0.0f, 1.0f, 0.0f));

    return { params.begin(), params.end() };
}

void DustCrateAudioProcessor::getStateInformation(juce::MemoryBlock& destData)
{
    auto state = apvts.copyState();
    std::unique_ptr<juce::XmlElement> xml(state.createXml());
    copyXmlToBinary(*xml, destData);
}

void DustCrateAudioProcessor::setStateInformation(const void* data, int sizeInBytes)
{
    std::unique_ptr<juce::XmlElement> xml(getXmlFromBinary(data, sizeInBytes));
    if (xml != nullptr && xml->hasTagName(apvts.state.getType()))
        apvts.replaceState(juce::ValueTree::fromXml(*xml));
}

juce::AudioProcessorEditor* DustCrateAudioProcessor::createEditor()
{
    return new DustCrateAudioProcessorEditor(*this);
}

juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new DustCrateAudioProcessor();
}
